"""Golden comparison for the jumpplus-coin-ledger report (local files only).

Compares workbooks generated by `python jumpplus_coin_ledger_report.py ...`
(local Golden Run) with the existing, manually produced Excel files of the
same month. No network access: it only opens the given local XLSX files.

Output: a JSON summary (row counts, totals, per-column mismatch counts and
up to N sample *keys* per mismatching column). Cell values are only written
to the report when --include-values is given, so the default report can be
shared without copying data.

Usage:
  python scripts/compare_coin_ledger_golden.py \
    --generated-app out/app.xlsx --golden-app golden/app.xlsx \
    --generated-web out/web.xlsx --golden-web golden/web.xlsx \
    --generated-product out/product.xlsx --golden-product golden/product.xlsx \
    --report out/golden_report.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from openpyxl import load_workbook

LEDGER_BLOCKS = {
    "app": {"合計": 4, "Apple": 16, "Google": 28},
    "web": {"WEB": 4},
}
APP_SUMMARY_SHEETS = ("サマリ", "サマリ (Apple)", "サマリ (Google)")
APP_DETAIL_SHEETS = ("有料話消費コイン（Apple）", "有料話消費コイン（Google）", "有料巻消費コイン（Apple）", "有料巻消費コイン（Google）")
WEB_SUMMARY_SHEETS = ("サマリ",)
WEB_DETAIL_SHEETS = ("有料話消費ポイント", "有料巻消費ポイント")


def _norm(value: Any) -> Any:
    """Normalizes representation-only differences (int vs float, Decimal,
    date vs 'YYYY-MM-DD' text, surrounding spaces, empty string vs None) so
    only real content differences are counted. Representation differences
    are reported separately under `value_types`."""
    if value is None:
        return None
    if isinstance(value, str):
        text = value.strip()
        return text if text else None
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float, Decimal)):
        number = float(value)
        return int(number) if number.is_integer() else round(number, 6)
    return value


def _type_name(value: Any) -> str:
    if value is None:
        return "empty"
    if isinstance(value, datetime):
        return "datetime"
    if isinstance(value, date):
        return "date"
    return type(value).__name__


_WORKBOOKS: dict[tuple[str, bool], Any] = {}


def _workbook(path: Path, *, data_only: bool = True):
    """Read-only workbook, opened once per (path, data_only) and reused --
    the monthly files are 5-16 MB, so re-opening per sheet is prohibitive."""
    key = (str(path), data_only)
    if key not in _WORKBOOKS:
        _WORKBOOKS[key] = load_workbook(path, read_only=True, data_only=data_only)
    return _WORKBOOKS[key]


def _close_workbooks() -> None:
    for wb in _WORKBOOKS.values():
        wb.close()
    _WORKBOOKS.clear()


def _sheet_rows(path: Path, sheet_name: str, *, data_only: bool = True, max_col: int = 8) -> dict[int, list[Any]]:
    ws = _workbook(path, data_only=data_only)[sheet_name]
    return {r: list(row) for r, row in enumerate(ws.iter_rows(min_col=1, max_col=max_col, values_only=True), start=1)}


def _table_refs(path: Path) -> dict[str, tuple[str, int]]:
    """{sheet name: (table ref, totalsRowCount)} read straight from the
    package parts (read-only openpyxl worksheets do not expose tables)."""
    import zipfile

    from lxml import etree

    m = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
    r_ns = "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}"
    out: dict[str, tuple[str, int]] = {}
    with zipfile.ZipFile(path) as zf:
        names = set(zf.namelist())
        wb = etree.fromstring(zf.read("xl/workbook.xml"))
        rels = {x.get("Id"): x.get("Target") for x in etree.fromstring(zf.read("xl/_rels/workbook.xml.rels"))}
        for sheet in wb.find(m + "sheets"):
            target = rels[sheet.get(r_ns + "id")]
            part = target[1:] if target.startswith("/") else "xl/" + target
            rels_part = part.rsplit("/", 1)[0] + "/_rels/" + part.rsplit("/", 1)[1] + ".rels"
            if rels_part not in names:
                continue
            tables = []
            for rel in etree.fromstring(zf.read(rels_part)):
                if rel.get("Type", "").endswith("/table"):
                    t = rel.get("Target")
                    table_part = t[1:] if t.startswith("/") else "xl/" + t.replace("../", "")
                    root = etree.fromstring(zf.read(table_part))
                    tables.append((root.get("ref"), int(root.get("totalsRowCount") or 0)))
            if len(tables) == 1:
                out[sheet.get("name")] = tables[0]
    return out


def _read_table(path: Path, sheet_name: str) -> tuple[list[str], list[list[Any]], list[Any] | None]:
    """(headers, data_rows, totals_row) of the sheet's single Excel Table."""
    from openpyxl.utils import range_boundaries

    refs = _table_refs(path)
    if sheet_name not in refs:
        raise SystemExit(f"{path.name}:{sheet_name}: expected exactly 1 table")
    ref, totals = refs[sheet_name]
    min_col, header_row, max_col, max_row = range_boundaries(ref)
    ws = _workbook(path)[sheet_name]
    values = [list(r) for r in ws.iter_rows(min_row=header_row, max_row=max_row, min_col=min_col, max_col=max_col, values_only=True)]
    values += [[None] * (max_col - min_col + 1)] * (max_row - header_row + 1 - len(values))
    headers = [str(v or "").strip() for v in values[0]]
    body = values[1 : len(values) - totals] if totals else values[1:]
    rows = [r for r in body if any(v not in (None, "") for v in r)]
    totals_row = values[-1] if totals else None
    return headers, rows, totals_row


def _compare_keyed(
    gen: tuple[list[str], list[list[Any]], Any],
    gold: tuple[list[str], list[list[Any]], Any],
    *,
    key_header: str,
    samples: int,
    include_values: bool,
) -> dict[str, Any]:
    gen_headers, gen_rows, _ = gen
    gold_headers, gold_rows, _ = gold
    result: dict[str, Any] = {
        "headers_equal": gen_headers == gold_headers,
        "generated_rows": len(gen_rows),
        "golden_rows": len(gold_rows),
    }
    if key_header not in gen_headers or key_header not in gold_headers:
        result["error"] = f"key header {key_header!r} missing"
        return result
    gi, oi = gen_headers.index(key_header), gold_headers.index(key_header)
    # A key may legitimately repeat (e.g. the same book content on two
    # source rows): group rows per key and compare each key's rows as a
    # multiset (paired after sorting) instead of letting a later row
    # overwrite an earlier one.
    gen_by: dict[Any, list[list[Any]]] = {}
    for row in gen_rows:
        gen_by.setdefault(_norm(row[gi]), []).append(row)
    gold_by: dict[Any, list[list[Any]]] = {}
    for row in gold_rows:
        gold_by.setdefault(_norm(row[oi]), []).append(row)
    only_gen = [k for k in gen_by if k not in gold_by]
    only_gold = [k for k in gold_by if k not in gen_by]
    result.update(
        {
            "duplicate_keys_generated": sum(1 for v in gen_by.values() if len(v) > 1),
            "duplicate_keys_golden": sum(1 for v in gold_by.values() if len(v) > 1),
            "only_in_generated": len(only_gen),
            "only_in_golden": len(only_gold),
            "only_in_generated_sample_keys": [str(k) for k in only_gen[:samples]],
            "only_in_golden_sample_keys": [str(k) for k in only_gold[:samples]],
        }
    )
    common = [k for k in gold_by if k in gen_by]
    result["keys_with_different_row_multiplicity"] = sum(1 for k in common if len(gen_by[k]) != len(gold_by[k]))
    gen_order = [_norm(r[gi]) for r in gen_rows if _norm(r[gi]) in gold_by]
    gold_order = [_norm(r[oi]) for r in gold_rows if _norm(r[oi]) in gen_by]
    result["row_order_equal"] = gen_order == gold_order
    result["row_order_position_matches"] = sum(1 for a, b in zip(gen_order, gold_order) if a == b)
    result["row_order_compared_positions"] = min(len(gen_order), len(gold_order))
    result["nat_text_cells_generated"] = sum(1 for r in gen_rows for v in r if isinstance(v, str) and v.strip() == "NaT")
    result["_gen_order"] = gen_order
    result["_gold_order"] = gold_order

    def _sorted_rows(rows: list[list[Any]]) -> list[list[Any]]:
        return sorted(rows, key=lambda r: tuple(str(_norm(v)) for v in r))

    pairs: list[tuple[Any, list[Any], list[Any]]] = []
    for k in common:
        for g_row, o_row in zip(_sorted_rows(gen_by[k]), _sorted_rows(gold_by[k])):
            pairs.append((k, g_row, o_row))

    def _sheet_sum(rows: list[list[Any]], idx: int) -> float | None:
        total = 0.0
        for r in rows:
            v = r[idx]
            if isinstance(v, (int, float, Decimal)) and not isinstance(v, bool):
                total += float(v)
            elif v not in (None, ""):
                return None
        return total

    columns: dict[str, Any] = {}
    for header in gold_headers:
        if header not in gen_headers:
            columns[header] = {"error": "missing in generated"}
            continue
        gc, oc = gen_headers.index(header), gold_headers.index(header)
        mismatched = []
        gen_types: dict[str, int] = {}
        gold_types: dict[str, int] = {}
        numeric_total_gen = numeric_total_gold = 0.0
        numeric = True
        for k, g_row, o_row in pairs:
            gv, ov = g_row[gc], o_row[oc]
            gen_types[_type_name(gv)] = gen_types.get(_type_name(gv), 0) + 1
            gold_types[_type_name(ov)] = gold_types.get(_type_name(ov), 0) + 1
            if _norm(gv) != _norm(ov):
                mismatched.append((k, gv, ov))
            for v, acc in ((gv, "g"), (ov, "o")):
                if isinstance(v, (int, float, Decimal)) and not isinstance(v, bool):
                    if acc == "g":
                        numeric_total_gen += float(v)
                    else:
                        numeric_total_gold += float(v)
                elif v not in (None, ""):
                    numeric = False
        entry: dict[str, Any] = {"mismatch_count": len(mismatched), "value_types": {"generated": gen_types, "golden": gold_types}}
        if mismatched:
            entry["sample_keys"] = [str(k) for k, _, _ in mismatched[:samples]]
            if include_values:
                entry["sample_values"] = [
                    {"key": str(k), "generated": str(gv), "golden": str(ov)} for k, gv, ov in mismatched[:samples]
                ]
        full_gen, full_gold = _sheet_sum(gen_rows, gc), _sheet_sum(gold_rows, oc)
        if full_gen is not None and full_gold is not None:
            entry["sheet_sum_generated"] = full_gen
            entry["sheet_sum_golden"] = full_gold
        if numeric:
            entry["sum_generated"] = numeric_total_gen
            entry["sum_golden"] = numeric_total_gold
        columns[header] = entry
    result["columns"] = columns
    return result


# Pre-separation Golden Masters (e.g. 2026-08) have no 出納 sheet: each ledger
# block sits below the table of the matching サマリ sheet, starting on the row
# after the one whose column A is "コイン種別".
GOLDEN_LEDGER_SUMMARY_SHEETS = {"合計": "サマリ", "Apple": "サマリ (Apple)", "Google": "サマリ (Google)"}


def _golden_ledger_first_row(rows: dict[int, list[Any]], block_name: str) -> int:
    for r in sorted(rows, reverse=True):
        if str(rows[r][0] or "").strip() == "コイン種別":
            return r + 1
    raise SystemExit(f"golden ledger block {block_name!r} not found")


def _ratio(numerator: Any, denominator: Any) -> Any:
    try:
        return numerator / denominator if denominator else "-"
    except TypeError:
        return "-"


_COLS = "ABCDEFGH"


def _compare_ledger(gen_path: Path, gold_path: Path, blocks: dict[str, int]) -> dict[str, Any]:
    gen_formulas = _sheet_rows(gen_path, "出納", data_only=False)
    gold_sheets = _workbook(gold_path).sheetnames
    out: dict[str, Any] = {}
    for name, first in blocks.items():
        if "出納" in gold_sheets:
            gold_rows, gold_first = _sheet_rows(gold_path, "出納"), first
            layout = "出納 sheet"
        else:
            sheet = GOLDEN_LEDGER_SUMMARY_SHEETS[name]
            gold_rows = _sheet_rows(gold_path, sheet)
            gold_first = _golden_ledger_first_row(gold_rows, name)
            layout = f"{sheet} (below table, row {gold_first})"
        mismatches = []
        labels_equal = True
        for offset in range(6):
            r, gr = first + offset, gold_first + offset
            gen_row = gen_formulas.get(r) or [None] * 8
            gold_row = gold_rows.get(gr) or [None] * 8
            if str(gen_row[0] or "").strip() != str(gold_row[0] or "").strip():
                labels_equal = False
            b, c, d, e = (gen_row[_COLS.index(col)] or 0 for col in "BCDE")
            expected = {"B": b, "C": c, "D": d, "E": e, "F": c + b - d + e, "G": _ratio(d, b), "H": _ratio(d, b + c)}
            for col, gen_value in expected.items():
                gold_value = gold_row[_COLS.index(col)]
                # Golden Masters saved by Excel can carry binary floating
                # point noise in computed cells (e.g. a 残高 cached as
                # N - 9.5e-07), so numeric cells compare with a tolerance.
                if isinstance(gen_value, (int, float)) and isinstance(gold_value, (int, float)):
                    same = abs(float(gen_value) - float(gold_value)) < 1e-6
                else:
                    same = _norm(gen_value) == _norm(gold_value)
                if not same:
                    mismatches.append(f"{col}{r}")
            for col, formula in (("F", "C{r}+B{r}-D{r}+E{r}"), ("G", "IFERROR(D{r}/B{r},\"-\")"), ("H", "IFERROR(D{r}/SUM(B{r}:C{r}),\"-\")")):
                if str(gen_row[_COLS.index(col)] or "").lstrip("=") != formula.format(r=r):
                    mismatches.append(f"{col}{r}:formula")
        out[name] = {"golden_layout": layout, "coin_labels_equal": labels_equal, "mismatched_cells": mismatches}
    return out


# ---------------------------------------------------------------------------
# Classification (PASS / ACCEPTED_DIFF / FAIL)
#
# Differences are never dropped: every one is counted, and an accepted
# difference carries the reason it was accepted (approved spec decisions,
# 2026-09-28). Anything not covered by a rule below is "unexpected".
# ---------------------------------------------------------------------------

ACCEPTED_REASONS = {
    "web_historical_ledger_drift": "WEB 出納の繰越(C)はBigQuery carried_over_coins_mを正とする。上流の後日補正による過去納品値との差(残高F・繰越込消費率Hは繰越に連動)",
    "current_master_additions": "話売商品は生成時点のraise_master_contents_works(episode)を正とする。現行マスタに追加されたID",
    "current_master_update": "話売商品は生成時点のマスタを正とする。価格・配信開始日・コミックスJDCN・コミックス巻数の更新",
    "golden_web_book_sheet_is_episode_copy": "2026-08 Golden MasterのWEB「有料巻消費ポイント」は話シートのコピーのため比較基準にしない",
}
PRODUCT_CURRENT_MASTER_COLUMNS = ("価格（コイン）", "配信開始日", "コミックスJDCN", "コミックス巻数")
TOTAL_COLUMNS = {"app": ("コイン消費合計", "消費コイン"), "web": ("ポイント消費合計", "消費ポイント")}


def _item(area: str, kind: str, count: int, *, accepted: str | None = None, note: str = "") -> dict[str, Any]:
    entry: dict[str, Any] = {"area": area, "kind": kind, "actual_diff_count": count}
    if accepted:
        entry["accepted_reason_code"] = accepted
        entry["accepted_reason"] = ACCEPTED_REASONS[accepted]
    if note:
        entry["note"] = note
    return entry


def _groups_equal(gen_order: list, gold_order: list, groups: dict[str, str]) -> bool | None:
    if not groups:
        return None
    try:
        return [groups[str(k)] for k in gen_order] == [groups[str(k)] for k in gold_order]
    except KeyError:
        return None


def _classify_keyed(area: str, sheet_result: dict[str, Any], *, product: bool, order_groups: dict[str, str]) -> tuple[list, list]:
    accepted, unexpected = [], []
    if not sheet_result["headers_equal"]:
        unexpected.append(_item(area, "headers", 1))
    for side in ("only_in_generated", "only_in_golden"):
        n = sheet_result[side]
        if n:
            if product and side == "only_in_generated":
                accepted.append(_item(area, side, n, accepted="current_master_additions"))
            else:
                unexpected.append(_item(area, side, n))
    if sheet_result.get("keys_with_different_row_multiplicity"):
        unexpected.append(_item(area, "row_multiplicity", sheet_result["keys_with_different_row_multiplicity"]))
    if sheet_result.get("nat_text_cells_generated"):
        unexpected.append(_item(area, "nat_text", sheet_result["nat_text_cells_generated"]))
    for col, c in sheet_result["columns"].items():
        if c.get("error"):
            unexpected.append(_item(area, f"column_missing:{col}", 1))
            continue
        if c["mismatch_count"]:
            if product and col in PRODUCT_CURRENT_MASTER_COLUMNS:
                accepted.append(_item(area, f"cell:{col}", c["mismatch_count"], accepted="current_master_update"))
            else:
                unexpected.append(_item(area, f"cell:{col}", c["mismatch_count"]))
        gen_types = {k for k in c["value_types"]["generated"] if k != "empty"}
        gold_types = {k for k in c["value_types"]["golden"] if k != "empty"}
        if gen_types and gold_types and gen_types != gold_types:
            note = f"generated={sorted(gen_types)} golden={sorted(gold_types)}"
            if product and col in PRODUCT_CURRENT_MASTER_COLUMNS:
                # e.g. the Golden's 2 non-integer prices: part of the same
                # accepted current-master price difference, not a writer type.
                accepted.append(_item(area, f"datatype:{col}", 1, accepted="current_master_update", note=note))
            else:
                unexpected.append(_item(area, f"datatype:{col}", 1, note=note))
    if not product and not sheet_result["row_order_equal"]:
        mismatched = sheet_result["row_order_compared_positions"] - sheet_result["row_order_position_matches"]
        within = _groups_equal(sheet_result["_gen_order"], sheet_result["_gold_order"], order_groups)
        note = "all differing positions are within equal sort-key (name_kana) groups" if within else ""
        unexpected.append(_item(area, "row_order", mismatched, note=note))
    return accepted, unexpected


def _check_expected(area: str, table: tuple, expected: dict[str, Any], total_header: str) -> list:
    headers, rows, _ = table
    problems = []
    if "rows" in expected and len(rows) != expected["rows"]:
        problems.append(_item(area, "expected_row_count", 1, note=f"generated={len(rows)} expected={expected['rows']}"))
    if "total" in expected:
        idx = headers.index(total_header)
        total = sum(float(r[idx] or 0) for r in rows)
        if abs(total - expected["total"]) > 1e-6:
            problems.append(_item(area, "expected_total", 1, note=f"generated={total} expected={expected['total']}"))
    return problems


def compare(args: argparse.Namespace) -> dict[str, Any]:
    expected = json.loads(Path(args.expected).read_text(encoding="utf-8")) if args.expected else {}
    order_groups = json.loads(Path(args.order_groups).read_text(encoding="utf-8")) if args.order_groups else {}
    report: dict[str, Any] = {"sections": {}}
    accepted: list = []
    unexpected: list = []
    pairs = (
        ("app", args.generated_app, args.golden_app, APP_SUMMARY_SHEETS, APP_DETAIL_SHEETS),
        ("web", args.generated_web, args.golden_web, WEB_SUMMARY_SHEETS, WEB_DETAIL_SHEETS),
    )
    for key, gen, gold, summaries, details in pairs:
        if not (gen and gold):
            continue
        gen, gold = Path(gen), Path(gold)
        section: dict[str, Any] = {"ledger": _compare_ledger(gen, gold, LEDGER_BLOCKS[key])}
        for block, result in section["ledger"].items():
            cells = result["mismatched_cells"]
            if not result["coin_labels_equal"]:
                unexpected.append(_item(f"{key}/ledger/{block}", "coin_labels", 1))
            if key == "web" and cells and all(c[0] in "CFH" and ":" not in c for c in cells):
                accepted.append(
                    _item(f"{key}/ledger/{block}", "cells:" + ",".join(cells), len(cells), accepted="web_historical_ledger_drift")
                )
            elif cells:
                unexpected.append(_item(f"{key}/ledger/{block}", "cells:" + ",".join(cells), len(cells)))
        summary_total, detail_total = TOTAL_COLUMNS[key]
        golden_episode_rows = None
        for sheet in summaries + details:
            is_summary = sheet in summaries
            gen_table, gold_table = _read_table(gen, sheet), _read_table(gold, sheet)
            area = f"{key}/{sheet}"
            sheet_expected = (expected.get(key) or {}).get(sheet, {})
            unexpected += _check_expected(area, gen_table, sheet_expected, summary_total if is_summary else detail_total)
            if sheet == details[0]:
                golden_episode_rows = gold_table[1]
            if key == "web" and sheet == details[-1] and golden_episode_rows is not None and gold_table[1] == golden_episode_rows:
                # Golden defect: validate the generated sheet independently instead.
                gen_keys = [r[0] for r in gen_table[1]]
                episode_keys = {r[0] for r in _read_table(gen, details[0])[1]}
                validation = {
                    "golden_sheet_equals_episode_sheet": True,
                    "generated_rows": len(gen_keys),
                    "generated_keys_unique": len(gen_keys) == len(set(gen_keys)),
                    "generated_keys_disjoint_from_episode": not (set(gen_keys) & episode_keys),
                    "nat_text_cells_generated": sum(1 for r in gen_table[1] for v in r if isinstance(v, str) and v.strip() == "NaT"),
                }
                section[sheet] = {"golden_comparison": "skipped", "validation": validation}
                accepted.append(
                    _item(area, "golden_sheet_not_comparable", len(gold_table[1]), accepted="golden_web_book_sheet_is_episode_copy")
                )
                if not (
                    validation["generated_keys_unique"]
                    and validation["generated_keys_disjoint_from_episode"]
                    and not validation["nat_text_cells_generated"]
                ):
                    unexpected.append(_item(area, "independent_validation", 1))
                continue
            result = _compare_keyed(
                gen_table,
                gold_table,
                key_header="作品名" if is_summary else "コンテンツID_Raise",
                samples=args.samples,
                include_values=args.include_values,
            )
            a, u = _classify_keyed(area, result, product=False, order_groups=(order_groups.get(key) or {}).get(sheet, {}))
            accepted += a
            unexpected += u
            section[sheet] = result
        report["sections"][key] = section
    if args.generated_product and args.golden_product:
        gen, gold = Path(args.generated_product), Path(args.golden_product)
        result = _compare_keyed(
            _read_table(gen, _workbook(gen).sheetnames[0]),
            _read_table(gold, _workbook(gold).sheetnames[0]),
            key_header="コンテンツID_Raise",
            samples=args.samples,
            include_values=args.include_values,
        )
        a, u = _classify_keyed("product", result, product=True, order_groups={})
        accepted += a
        unexpected += u
        report["sections"]["product"] = result

    for section in report["sections"].values():
        for value in [section] if "columns" in section else section.values():
            if isinstance(value, dict):
                value.pop("_gen_order", None)
                value.pop("_gold_order", None)
    report["classification"] = {
        "verdict": "FAIL" if unexpected else ("PASS_WITH_ACCEPTED_DIFFS" if accepted else "PASS"),
        "unexpected_diff_count": sum(i["actual_diff_count"] for i in unexpected),
        "accepted_diff_count": sum(i["actual_diff_count"] for i in accepted),
        "unexpected": unexpected,
        "accepted": accepted,
    }
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    for kind in ("app", "web", "product"):
        parser.add_argument(f"--generated-{kind}")
        parser.add_argument(f"--golden-{kind}")
    parser.add_argument("--report", required=True)
    parser.add_argument("--expected", help="JSON {app|web: {sheet: {rows, total}}} checked against the generated sheets")
    parser.add_argument(
        "--order-groups",
        help="JSON {app|web: {sheet: {key: sort-key group}}}; a row-order difference is annotated when every "
        "differing position falls inside one group (ties of the documented sort key)",
    )
    parser.add_argument("--samples", type=int, default=5)
    parser.add_argument("--include-values", action="store_true", help="also write mismatching cell values (local use only)")
    args = parser.parse_args(argv)
    try:
        report = compare(args)
    finally:
        _close_workbooks()
    Path(args.report).write_text(json.dumps(report, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    c = report["classification"]
    print(f"written: {args.report}")
    print(f"verdict: {c['verdict']} unexpected={c['unexpected_diff_count']} accepted={c['accepted_diff_count']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
